<?xml version="1.0" encoding="UTF-8"?>
<testsuite name="Click_Button_Functionality"
           tests="2"
           failures="1"
           errors="0"
           skipped="1"
           time="0.000">
  <properties />
            <testcase name="setUp" time="0.000" classname="com.linkedin.cases.CreateNewAccount">
                <failure type="java.lang.NullPointerException"
                  message="null value in entry: desiredCapabilities=null"
              >
<![CDATA[java.lang.NullPointerException: null value in entry: desiredCapabilities=null
  com.google.common.collect.CollectPreconditions.checkEntryNotNull(CollectPreconditions.java:33)
  com.google.common.collect.ImmutableMap.entryOf(ImmutableMap.java:135)
  com.google.common.collect.ImmutableMap$Builder.put(ImmutableMap.java:206)
  org.openqa.selenium.remote.RemoteWebDriver.startSession(RemoteWebDriver.java:234)
  org.openqa.selenium.remote.RemoteWebDriver.<init>(RemoteWebDriver.java:126)
  org.openqa.selenium.remote.RemoteWebDriver.<init>(RemoteWebDriver.java:153)
  com.linkedin.init.SeleniumInit.setUp(SeleniumInit.java:304)
  sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
  sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
  sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
  java.lang.reflect.Method.invoke(Unknown Source)
  org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:84)
  org.testng.internal.Invoker.invokeConfigurationMethod(Invoker.java:564)
  org.testng.internal.Invoker.invokeConfigurations(Invoker.java:213)
  org.testng.internal.Invoker.invokeMethod(Invoker.java:653)
  org.testng.internal.Invoker.invokeTestMethod(Invoker.java:901)
  org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1231)
  org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:127)
  org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:111)
  org.testng.TestRunner.privateRun(TestRunner.java:767)
  org.testng.TestRunner.run(TestRunner.java:617)
  org.testng.SuiteRunner.runTest(SuiteRunner.java:334)
  org.testng.SuiteRunner.runSequentially(SuiteRunner.java:329)
  org.testng.SuiteRunner.privateRun(SuiteRunner.java:291)
  org.testng.SuiteRunner.run(SuiteRunner.java:240)
  org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
  org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
  org.testng.TestNG.runSuitesSequentially(TestNG.java:1224)
  org.testng.TestNG.runSuitesLocally(TestNG.java:1149)
  org.testng.TestNG.run(TestNG.java:1057)
  org.testng.remote.RemoteTestNG.run(RemoteTestNG.java:111)
  org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:204)
  org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:175)
]]>
      </failure>

          </testcase>
  
            <testcase name="click_joinnow_button" time="0.0" classname="com.linkedin.cases.CreateNewAccount">
          <skipped />
    </testcase>
  
  
</testsuite>
